SELECT TOP (1) [NCN].[COD_CONCEPTO]
      ,[NCN].[DESC_CONCEPTO]
      ,[NE].[ID_EMPLEADO]
      ,[RSI].[DOCUMENTO] 
	  ,[RSI].[APELLIDOS]
      ,[RSI].[NOMBRES]	  
      ,[NND].[VAL_NOMINA]
	  ,[NND].[CANTIDAD]	  
  FROM [dbo].[REG_SOLICITUDES_INGRESOS] AS [RSI] 
  INNER JOIN [dbo].[NOM_EMPLEADOS] AS [NE] ON ([RSI].[ID_SOLICITUD] = [NE].[ID_SOLICITUD])
  INNER JOIN [dbo].[NOM_NOMINA_DEFINITIVA] AS [NND] ON ([NE].[ID_EMPLEADO] = [NND].[ID_EMPLEADO] )
  INNER JOIN [dbo].[NOM_CONCEPTOS_NOMINA] AS [NCN] ON ([NND].[ID_CONCEPTO] = [NCN].[ID_CONCEPTO] )
  ORDER BY [NND].[FCH_CRE] DESC