USE [PruebaNexarte];
GO
DROP PROCEDURE IF EXISTS [dbo].[USP_CONSULTA_NOMINA_POR_DOCUMENTO] ;
GO
CREATE PROCEDURE [dbo].[USP_CONSULTA_NOMINA_POR_DOCUMENTO] 
	@DOC_IDENTIDAD VARCHAR(50),
	@Evento NUMERIC (5),
	@Usuario VARCHAR(50) = ADMIN,
	@REGISTRO_NOM_NOMINA_DEFINITIVA NUMERIC(18) = NULL,
	@ID_CONCEPTO INT = NULL,
	@VAL_NOMINA MONEY = NULL,
	@CANTIDAD INT = NULL
AS
BEGIN
	SET LANGUAGE us_english;  

	DECLARE @OPERACION NVARCHAR(50),@DESCRIPCION_EVENTO NVARCHAR(MAX);

	IF @Evento = 1 BEGIN
		SET @OPERACION='Consulta';
		SET @DESCRIPCION_EVENTO = CONCAT('Se consultan las nóminas del cliente con identificación : ', @DOC_IDENTIDAD) ;

		SELECT [NND].[REGISTRO]
			,[NCN].[COD_CONCEPTO]
			,[NCN].[DESC_CONCEPTO]
			,[NE].[ID_EMPLEADO]
			,[RSI].[DOCUMENTO] 
			,[RSI].[APELLIDOS]
			,[RSI].[NOMBRES]	  
			,[NND].[VAL_NOMINA]
			,[NND].[CANTIDAD]	  
		FROM [dbo].[REG_SOLICITUDES_INGRESOS] AS [RSI] 
		INNER JOIN [dbo].[NOM_EMPLEADOS] AS [NE] ON ([RSI].[ID_SOLICITUD] = [NE].[ID_SOLICITUD])
		INNER JOIN [dbo].[NOM_NOMINA_DEFINITIVA] AS [NND] ON ([NE].[ID_EMPLEADO] = [NND].[ID_EMPLEADO] )
		INNER JOIN [dbo].[NOM_CONCEPTOS_NOMINA] AS [NCN] ON ([NND].[ID_CONCEPTO] = [NCN].[ID_CONCEPTO] )
		WHERE [NND].[FCH_CRE] >= CONVERT(DATETIME, '01/01/2014', 101) AND [RSI].[DOCUMENTO] = @DOC_IDENTIDAD;
	END;

	IF @Evento = 2 BEGIN

		SET @OPERACION='Actualizar';
		SET @DESCRIPCION_EVENTO = CONCAT('Se actualiza la nómina "',@REGISTRO_NOM_NOMINA_DEFINITIVA,'"  del cliente con identificación :', @DOC_IDENTIDAD) ;

		UPDATE [dbo].[NOM_NOMINA_DEFINITIVA]
		SET [ID_CONCEPTO] = @ID_CONCEPTO
			,[VAL_NOMINA] = @VAL_NOMINA
			,[CANTIDAD] = @CANTIDAD
		WHERE [REGISTRO] = @REGISTRO_NOM_NOMINA_DEFINITIVA AND
		EXISTS (SELECT [RSI].[DOCUMENTO] 
			FROM [dbo].[REG_SOLICITUDES_INGRESOS] AS [RSI] 
			INNER JOIN [dbo].[NOM_EMPLEADOS] AS [NE] ON ([RSI].[ID_SOLICITUD] = [NE].[ID_SOLICITUD])
			INNER JOIN [dbo].[NOM_NOMINA_DEFINITIVA] AS [NND] ON ([NE].[ID_EMPLEADO] = [NND].[ID_EMPLEADO] )
			WHERE [RSI].[DOCUMENTO] = @DOC_IDENTIDAD
		); 		
	END;
	
	IF @Evento = 3 BEGIN

		SET @OPERACION='Eliminar';
		SET @DESCRIPCION_EVENTO = CONCAT('Se elimina la nómina "',@REGISTRO_NOM_NOMINA_DEFINITIVA,'"  del cliente con identificación :', @DOC_IDENTIDAD) ;

		DELETE FROM [dbo].[NOM_NOMINA_DEFINITIVA] WHERE [REGISTRO] = @REGISTRO_NOM_NOMINA_DEFINITIVA AND
		EXISTS (SELECT [RSI].[DOCUMENTO] 
			FROM [dbo].[REG_SOLICITUDES_INGRESOS] AS [RSI] 
			INNER JOIN [dbo].[NOM_EMPLEADOS] AS [NE] ON ([RSI].[ID_SOLICITUD] = [NE].[ID_SOLICITUD])
			INNER JOIN [dbo].[NOM_NOMINA_DEFINITIVA] AS [NND] ON ([NE].[ID_EMPLEADO] = [NND].[ID_EMPLEADO] )
			WHERE [RSI].[DOCUMENTO] = @DOC_IDENTIDAD
		); 		
	END;

	INSERT INTO [dbo].[LOG_CONSULTA_NOM_NOMINA_DEFINITIVA]
           ([USUARIO]
           ,[FECHA]
           ,[OPERACION]
           ,[DESCRIPCION_EVENTO])
     VALUES
           (@Usuario
           ,GETDATE()
           ,@OPERACION
           ,@DESCRIPCION_EVENTO);
END;
