//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaWebNexarte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_CONSULTA_NOM_NOMINA_DEFINITIVA
    {
        public int ID_REGISTRO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string OPERACION { get; set; }
        public string DESCRIPCION_EVENTO { get; set; }
    }
}
